Repository rpotter12/whatsapp-play, pull requests merged in 2020-03, with the labels that each got.

#160 screenshot added! :sparkle: resolved issues and working fine
  screenshots/screenshot-wplay.png
  wplay/utils/browser_config.py
Labels: GSSoC 2020

#159 Refactorized session management and removed recursion
  requirements.txt
  wplay/utils/session_manager.py
Labels: GSSoC 2020

#172 wplay-gui initial setup issue #43
  .gitignore
  wplay_gui/wplay/.gitignore
  wplay_gui/wplay/README.md
  wplay_gui/wplay/package-lock.json
  wplay_gui/wplay/package.json
  wplay_gui/wplay/public/electron.js
  wplay_gui/wplay/public/favicon.ico
  wplay_gui/wplay/public/index.html
  wplay_gui/wplay/public/logo192.png
  wplay_gui/wplay/public/logo512.png
  wplay_gui/wplay/public/manifest.json
  wplay_gui/wplay/public/robots.txt
  wplay_gui/wplay/src/App.css
  wplay_gui/wplay/src/App.js
  wplay_gui/wplay/src/index.css
  wplay_gui/wplay/src/index.js
Labels: GSSoC 2020, medium

#168 Add screenshot of tracking command
  Tracking_Execution.png
Labels: GSSoC 2020, beginner

#176 Add gitpod config
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
Labels: GSSoC 2020, easy

#170 adding screenshots
  screenshots/Screenshot 2020-03-02 at 3.54.26 PM.png
  screenshots/Screenshot 2020-03-02 at 4.30.49 PM.png
  screenshots/Screenshot 2020-03-02 at 4.31.13 PM.png
  screenshots/Screenshot 2020-03-02 at 4.31.21 PM.png
Labels: GSSoC 2020, beginner

#190 Create screenshot-atul
  screenshots/screenshot-atul
Labels: beginner, gssoc20

#197 Add files via upload
  screenshots/shivam_install.png
  screenshots/shivam_tracking.png
Labels: beginner, gssoc20

#193 Adding Installation - Issue #145
  screenshots/BhanujaAggarwal.png
Labels: beginner, gssoc20

#184 Issue 130 : Option to manually select target
  wplay/__main__.py
  wplay/messageblast.py
  wplay/messagetimer.py
  wplay/onlinetracker.py
  wplay/utils/target_select.py
  wplay/wchat.py
Labels: gssoc20, hard

#201 wplay issue #145
  Beginners.docx
  Screenshot
  screenshots/Beginners.docx
  screenshots/image.png
Labels: beginner, gssoc20

#206 Installing software - Screenshot (#145)
  screenshots/ss-soham.png
Labels: beginner, gssoc20

#195 #144-Get target info
  wplay/utils/helpers.py
  wplay/utils/target_search.py
Labels: gssoc20, hard

#214 added screenshots of successful software installation and tracking
  screenshots/Installation.png
  screenshots/run.png
  screenshots/track.jpg
Labels: beginner, gssoc20

#216 Add files via upload
  screenshots/zulkernine_executingTrackingCommand.png
Labels: beginner, gssoc20

#218 Installed and tracked
  screenshots/Nishtha3512_img1.png
  screenshots/Nishtha3512_img2.png
  screenshots/Nishtha3512_img3.png
Labels: beginner, gssoc20

#213 Adding GitHub Actions
  .github/workflows/greetings.yml
  .github/workflows/label.yml
  .github/workflows/stale.yml
Labels: easy, gssoc20

#220 Fix122logg
  wplay/__main__.py
  wplay/messageblast.py
  wplay/messagetimer.py
  wplay/onlinetracker.py
  wplay/utils/Logger.py
  wplay/utils/browser_config.py
  wplay/utils/io.py
  wplay/utils/target_data.py
  wplay/utils/target_search.py
  wplay/wchat.py
Labels: gssoc20, medium

#221 Added Scheduler for messages
  wplay/__main__.py
  wplay/scheduleMessage.py
Labels: gssoc20, hard

#231 #143 type annotations added according to python3
  wplay/__main__.py
  wplay/messageblast.py
  wplay/messagetimer.py
  wplay/onlinetracker.py
  wplay/savechat.py
  wplay/scheduleMessage.py
  wplay/tgbot.py
  wplay/utils/Logger.py
  wplay/utils/browser_config.py
  wplay/utils/io.py
  wplay/utils/session_manager.py
  wplay/utils/target_data.py
  wplay/utils/target_search.py
  wplay/wchat.py
Labels: easy, gssoc20

#232 Update for stale.yml
  .github/workflows/stale.yml
Labels: gssoc20

#239 Added issue template
  .github/IssueTemplate/BugReportTemplate.md
  .github/IssueTemplate/FeatureRequestTemplate.md
Labels: easy, gssoc20

#222 wchat Updated to change target person (#217)
  wplay/utils/io.py
  wplay/wchat.py
Labels: easy, gssoc20

#235 wplay screenshot of installation
  screenshots/wplay-screenshots3.PNG
  screenshots/wplay_screenshot.PNG
  screenshots/wplay_screenshot_2.PNG
Labels: beginner, gssoc20

#250 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: easy, gssoc20

#246 File Sharing feature added(Isuue #244)
  wplay/utils/helpers.py
  wplay/utils/io.py
  wplay/wchat.py
Labels: gssoc20, hard

#248 Update README.md
  README.md
  images/usage.png
  settings.cfg
  wplay/changeAbout.py
Labels: beginner, gssoc20

#256 Feature: Target a specific number
  wplay/__main__.py
  wplay/scheduleMessage.py
  wplay/utils/target_search.py
Labels: gssoc20, hard

#257 Revert 256 develop
  wplay/__main__.py
  wplay/scheduleMessage.py
  wplay/utils/target_search.py
Labels: beginner, gssoc20

#259 Added CODE_OF_CONDUCT.md
  CodeOfConduct.md
Labels: easy, gssoc20

#258 News(idea) #80 resolved
  README.md
  wplay/__main__.py
  wplay/changeAbout.py
  wplay/wnews.py
Labels: gssoc20, hard

#263 Get all types of news in wnews
  wplay/wnews.py
Labels: gssoc20, medium

#265 updated requirements.txt to include newsapi and dotenv package
  requirements.txt
Labels: beginner, gssoc20

#266 Download all the images of contacts
  README.md
  wplay/__main__.py
  wplay/get_media.py
  wplay/media_images/Screenshot (57).jpg
  wplay/wnews.py
Labels: gssoc20, hard

#249 #82 get number of all targets
  wplay/messageblast.py
  wplay/messagetimer.py
  wplay/onlinetracker.py
  wplay/utils/target_search.py
  wplay/wchat.py
Labels: gssoc20, medium
