Repository rpotter12/whatsapp-play, pull requests merged in 2020-05, with the labels that each got.

#324 download media
  tests/test_helpers.py
  wplay/__main__.py
  wplay/download_media.py
  wplay/utils/helpers.py
Labels: gssoc20, hard

#328 Receive messages in wchat script successfully in terminal chat whole chat displayed automatically.
  wplay/terminal_chat.py
Labels: gssoc20, medium

#333 Google search added successfully in chatbot
  requirements.txt
  wplay/chatbot.py
Labels: easy, gssoc20

#338 New Screenshot
  screenshots/Ank_wplay.PNG
Labels: beginner, gssoc20

#339 Added screenshot of software
  screenshots/m-code12.png
Labels: beginner, gssoc20

#340 Google search for image sends screenshot of webpage successfully added.
  wplay/chatbot.py
  wplay/terminal_chat.py
  wplay/utils/helpers.py
Labels: easy, gssoc20

#346 get_news working successfully now.
  README.md
  wplay/get_news.py
Labels: beginner, gssoc20

#342 Google maps feature added to chatbot successfully.
  wplay/chatbot.py
Labels: easy, gssoc20

#352 Selecting the target manually now works for -wtf command successfully.
  wplay/utils/target_select.py
Labels: easy, gssoc20

#357 Save chat for a target.
  README.md
  wplay/__main__.py
  wplay/save_chat.py
  wplay/utils/helpers.py
Labels: gssoc20, hard

#356 update requirements.txt as per current project requirements
  requirements.txt
Labels: beginner, gssoc20

#349 -wa command working successfully now
  README.md
  wplay/about_changer.py
Labels: beginner, gssoc20

#350 Intermediate of a conversation added successfully.
  README.md
  wplay/__main__.py
  wplay/about_changer.py
  wplay/chat_intermediator.py
  wplay/save_chat.py
  wplay/terminal_chat.py
  wplay/utils/io.py
Labels: gssoc20, hard

#364 Change about from terminal(customized)
  wplay/__main__.py
  wplay/about_changer.py
Labels: easy, gssoc20

#367 Profile picture downloaded target specific sucessfully added.
  wplay/__main__.py
  wplay/profile_download.py
Labels: easy, gssoc20

#369 Comman line argument error resolved
  wplay/__main__.py
  wplay/chat_intermediator.py
  wplay/terminal_chat.py
Labels: beginner, gssoc20

#370 last msg received in group
  wplay/terminal_chat.py
Labels: beginner, gssoc20
