Repository rpotter12/whatsapp-play, pull requests merged in 2020-04, with the labels that each got.

#264 #102 Automated unit test case written successfully for kill_child_process.py
  tests/test_func.py
  tests/test_kill_child_process.py
Labels: gssoc20, medium

#272 Automated unit test case added for Logger.py successfully.
  tests/test_logger.py
Labels: gssoc20, medium

#275 #145 installed and executed successfully
  screenshots/VaishSiddharth_installed.png
  screenshots/VaishSiddharth_wplay.png
Labels: beginner, gssoc20

#274 Get selected group details
  wplay/utils/helpers.py
  wplay/utils/target_search.py
Labels: gssoc20, medium

#269 Display all news in changeAbout
  README.md
  wplay/changeAbout.py
  wplay/get_media.py
Labels: gssoc20, medium

#291 added check to see if contact name entered is valid, if not, program exits
  wplay/utils/target_search.py
Labels: beginner, gssoc20

#294 #21 Fix21docker image
  Dockerfile
Labels: gssoc20, medium

#297 #102 Automated unit test written for helper.py
  tests/test_helpers.py
Labels: beginner, gssoc20

#288 Broadcast Message to numbers given in a file ( regarding #273)
  wplay/__main__.py
  wplay/broadcast_message.py
Labels: gssoc20, hard

#300 All Test files updated according to updated logger class and helper file.
  tests/test_helpers.py
  tests/test_kill_child_process.py
  tests/test_logger.py
  wplay/__main__.py
  wplay/utils/Logger.py
  wplay/utils/helpers.py
Labels: easy, gssoc20

#303 .travis.yml file added successfully
  .travis.yml
Labels: gssoc20, medium

#306 Successfully Build travis on Travis CI
  .travis.yml
  tests/test_helpers.py
Labels: gssoc20, medium

#304 Installed the software and ran the tracking commands
  screenshots/Screenshot (61).png
  screenshots/Screenshot (62).png
Labels: beginner, gssoc20

#307 successful installation and executing tracking command
  screenshots/shreya-installation.JPG
Labels: beginner, gssoc20

#311 Install the software and execute the tracking command successfully, P…
  screenshots/Screenshot (61).png
  screenshots/Screenshot (62).png
  screenshots/screenshot_001.PNG
  screenshots/screenshot_002.PNG
  screenshots/screenshot_003.PNG
  screenshots/shreya-installation.JPG
Labels: beginner, gssoc20

#313 screenshots added
  screenshots/Swadesh13_screenshot1.png
  screenshots/Swadesh13_screenshot2.png
  screenshots/Swadesh13_screenshot3.png
Labels: beginner, gssoc20

#316 Location_finder file added successfully
  wplay/__main__.py
  wplay/location_finder.py
  wplay/target_info.py
Labels: gssoc20, hard

#318 screenshots upload
  screenshots/Screenshot (4).png
  screenshots/Screenshot (5).png
Labels: beginner, gssoc20

#305 Screenshot of installation
  screenshots/shivank_install
  screenshots/shivank_tracking.png
Labels: beginner, gssoc20

#319 Target info
  README.md
  requirements.txt
  wplay/__main__.py
  wplay/target_info.py
  wplay/utils/target_search.py
Labels: gssoc20, medium

#325 Installed Software
  screenshots/satyam.jpg
Labels: beginner, gssoc20
